version: '3'

services:
  Jenkins:
    image: jenkins/jenkins:lts-alpine
    environment:
      - JENKINS_PASSWORD=admin
      - JENKINS_USERNAME=admin
    security_opt:
      - seccomp:unconfined
    volumes:
      - jenkins:/var/jenkins_home
    labels:
      application: jenkins
    networks:
      - local
    ports:
      - 50000:50000
      - 8080:8080

volumes:
  jenkins:

networks:
  local:
